server.port=8080
#management.endpoints.web.exposure.include=*
#management.endpoints.health.show-details=always
#
#spring.datasource.url=jdbc:mysql://localhost:3306/Django?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.hibernate.ddl-auto = update