spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Django?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: admin
